import type { CalendarEvent } from '../types/database';

export const LOCAL_STORAGE_KEYS = {
  OWNER_TOKEN: 'liberal_calendar_owner_token',
  VIEW_MODE: 'liberal_calendar_view_mode',
  FILTER_STATE: 'liberal_calendar_filter_state',
  OFFLINE_EVENTS: 'liberal_calendar_offline_events',
  MEMBER_NAME: 'liberal_calendar_member_name',
};

// Clean sample events for shared calendar
export const SAMPLE_INITIAL_EVENTS: CalendarEvent[] = [
  {
    id: 'evt-sample-1',
    title: 'Họp giao ban toàn công ty đầu tuần',
    description: 'Rà soát tiến độ dự án tuần cũ và phân công kế hoạch công việc tuần mới.',
    start_at: new Date(new Date().setHours(0, 57, 0, 0)).toISOString(),
    end_at: new Date(new Date().setHours(2, 27, 0, 0)).toISOString(),
    all_day: false,
    location: 'Phòng họp Tầng 3',
    meeting_url: 'https://meet.google.com/abc-defg-hij',
    status: 'scheduled',
    tag: 'Họp hành',
    timezone: 'Asia/Ho_Chi_Minh',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'evt-sample-2',
    title: 'Deadline nộp Báo cáo Doanh thu',
    description: 'Yêu cầu các trưởng bộ phận chốt số liệu và gửi file.',
    start_at: new Date(new Date().setHours(4, 57, 0, 0)).toISOString(),
    end_at: new Date(new Date().setHours(5, 57, 0, 0)).toISOString(),
    all_day: false,
    location: 'Hệ thống ERP',
    status: 'scheduled',
    tag: 'Deadline',
    timezone: 'Asia/Ho_Chi_Minh',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'evt-sample-3',
    title: 'Teambuilding & Tiệc mừng Sinh nhật thành viên',
    description: 'Chương trình giao lưu nội bộ công ty tại sảnh chính.',
    start_at: new Date(new Date().setHours(23, 57, 0, 0)).toISOString(),
    end_at: new Date(new Date().setHours(2, 57, 0, 0) + 86400000).toISOString(),
    all_day: false,
    location: 'Sảnh sự kiện Tầng 1',
    status: 'scheduled',
    tag: 'Sự kiện',
    timezone: 'Asia/Ho_Chi_Minh',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'evt-sample-4',
    title: 'Review dự án & Kế hoạch triển khai Q3',
    description: 'Báo cáo chi tiết kết quả kinh doanh và chuẩn bị nguồn lực.',
    start_at: new Date(new Date().setHours(10, 0, 0, 0)).toISOString(),
    end_at: new Date(new Date().setHours(11, 30, 0, 0)).toISOString(),
    all_day: false,
    location: 'Phòng họp Tầng 2',
    status: 'scheduled',
    tag: 'Họp đánh giá',
    timezone: 'Asia/Ho_Chi_Minh',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'evt-sample-5',
    title: 'Đào tạo nội bộ: Kỹ năng giao tiếp & Làm việc nhóm',
    description: 'Khóa học phát triển kỹ năng mềm cho nhân sự.',
    start_at: new Date(new Date().setHours(15, 0, 0, 0)).toISOString(),
    end_at: new Date(new Date().setHours(16, 30, 0, 0)).toISOString(),
    all_day: false,
    location: 'Phòng Đào tạo Tầng 1',
    status: 'completed',
    tag: 'Sự kiện nội bộ',
    timezone: 'Asia/Ho_Chi_Minh',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }
];
